### ISSUE TITLE
ORMDatabaseTool is using 'master' instead of 'primary' when having replicas

### ISSUE THREAD

**Issue by alleknalle** [liip/LiipTestFixturesBundle#180]
Hi there,

I'm using Doctrine with the replica functionality. When I'm trying to load fixtures, I get a SyntaxErrorException when the bundle is trying to create the database. After some debugging I found out that in https://github.com/liip/LiipTestFixturesBundle/blob/2.x/src/Services/DatabaseTools/ORMDatabaseTool.php#L150 'master' is used.   Doctrine switched from master/slaves to primary/replicas in doctrine-bundle version 2.2.

Could you please update this as well?

**Comment by alexislefebvre** [comment]
Hi, could you please share the config that is used to connect to the database? Do you use the replica during the tests?

Please try #181, this may work.

**Comment by alleknalle** [comment]
Hi,

my config is:

```
doctrine:
  dbal:
    url: '%env(resolve:DATABASE_WRITER_URL)%'
    replicas:
      reader:
        url: '%env(resolve:DATABASE_READER_URL)%'
```

This is the config for all environment, including test.

I've tried your fix in https://github.com/liip/LiipTestFixturesBundle/pull/181 and that seems to work :-)
