### ISSUE TITLE
Fixture refs and sqlite caching

### ISSUE THREAD

**Issue by tiberiu89** [liip/LiipTestFixturesBundle#19]
It seems that loading fixtures and setting references are not working when the sqlite caching is enabled. It gives an array to string conversion error.

**Comment by magnetik** [comment]
Cannot confirm as I'm using sqlite cache & reference extensively.

Maybe you can share more code?

**Comment by tiberiu89** [comment]
Not much code to share. So I'm using standard doctrine fixtures for a symfony app, set some references in there(I'm using value objects and  custom doctrine types if relevant) call ->persist() and then ->setReference(...)

Then in my tests, I have a base class web test case extending `Liip\FunctionalTestBundle\Test\WebTestCase` with the following setup(taken from the class)

```php
    use FixturesTrait;

    /** @var KernelBrowser */
    protected $client;

    /** @var ReferenceRepository */
    protected static $fixtures;

    public static function setUpBeforeClass()
    {
        static::$fixtures = null;
    }

    public function setUp()
    {
        $this->client = $this->makeClient();

        // we load fixtures once per test suite so data is kept between tests
        // might as well work with `@depends`  annotations
        if (!static::$fixtures) {
            static::$fixtures = $this->loadFixtures([TestFixtures::class])
                ->getReferenceRepository();
        }
    }
```

I keep fxtures static there and try to instantiate it only once for each test case. Pretty much else is standard functional tests.  The doctrine test config is 

```yml
doctrine:
  dbal:
    driver: 'pdo_sqlite'
    path: '%kernel.cache_dir%/test.db'
    charset: utf8
```

Tests run fine as long as I use it without db cache, but once I add this to the config
```yml
liip_functional_test: ~
liip_test_fixtures:
  cache_db:
    sqlite: liip_test_fixtures.services_database_backup.sqlite
```

it will crash subsequent tests. I can see some files created in the cache directory(test_sqlite_somehash.db and .db.ser)

The error is as described above and it happens on this line
`static::$fixtures = $this->loadFixtures([TestFixtures::class])`, and by the looks of it, only when trying to recreate it from the cached db files
