### ISSUE TITLE
[Bug]: Nonexistant service for DB backup does not fail

### ISSUE THREAD

**Issue by tarjei** [liip/LiipTestFixturesBundle#213]
### Preconditions

Latest liip test fixtures bundle.

### Steps to reproduce

Hi had this config:

```yaml
liip_test_fixtures:
   cache_db:
    sqlite: liip_test_fixtures.services_database_backup.sqlite

```

The service  `liip_test_fixtures.services_database_backup.sqlite` has been renamed (AFAIK) to Liip\TestFixturesBundle\Services\DatabaseBackup\SqliteDatabaseBackup but loadFixtures() will function as normal **but be very slow** due to DB backups not working.

### Expected result

loadFixtures() should fail. 

### Actual result

loadFixtures gets a lot slower than expected.
