### ISSUE TITLE
Question: cached database with GitLab CI pipeline

### ISSUE THREAD

**Issue by ahmed-bhs** [liip/LiipTestFixturesBundle#239]
When using LiipFunctionalBundle cached database with gitalb ci pipeline, does there any need to cache some data between pipelines ?

```
#https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/database.md#tips-for-fixture-loading-tests
liip_test_fixtures:
    cache_db:
        sqlite: 'Liip\TestFixturesBundle\Services\DatabaseBackup\SqliteDatabaseBackup'

```

Cheers
