### ISSUE TITLE
[Bug]: mysqldump: unknown variable 'column-statistics=0' error

### ISSUE THREAD

**Issue by ahmad-rahnavard** [liip/LiipTestFixturesBundle#251]
### Preconditions

PHP: 8.1.25
Symfony: 5.4
LiipTestFixturesBundle: 2.6.0
DB: mariadb:10.5 (docker container with exposed port)

### Steps to reproduce

The bundle config:
```yaml
liip_test_fixtures:
    keep_database_and_schema: false
    cache_metadata: true
    cache_db:
        mysql: 'Liip\TestFixturesBundle\Services\DatabaseBackup\MysqlDatabaseBackup'
```

### Expected result

Tests should run without any issues and faster than when you set `cache_db: ~`

### Actual result

Getting the following error in tests. which also results in some failing tests.

```
mysqldump: unknown variable 'column-statistics=0'
```

NOTE: When I run the tests separately, I don't see any issues, but running multiple tests together results in the error above.

Removing the `--column-statistics=0` option from this line https://github.com/liip/LiipTestFixturesBundle/blob/2.x/src/Services/DatabaseBackup/MysqlDatabaseBackup.php#L78 fixed the issue for me.
