### ISSUE TITLE
Caching mysql database with its data

### ISSUE THREAD

**Issue by emr** [liip/LiipTestFixturesBundle#75]
While running all my e2e tests, the bundle caches the test database and restores it when it passes to another test. But it does not backup only the database schema, it also backup the test data. So when PHPUnit passes to another test, the database initializes with the previous tests' data. And occurs unexpected results.

### Preconditions
Package versions
```json
"liip/functional-test-bundle": "4.2.0",
"liip/test-fixtures-bundle": "1.9.1",
"doctrine/doctrine-bundle": "1.12.10",
"doctrine/common": "2.13.3",
"doctrine/dbal": "2.10.4",
"doctrine/orm": "2.7.4"
```

### Steps to reproduce
My config
```yaml
liip_functional_test: ~
liip_test_fixtures:
  cache_db:
    mysql: liip_test_fixtures.services_database_backup.mysql
```
My test case
```php

class E2eTestCase extends TestCase
{
    use FixturesTrait;

    protected function setUp(): void
    {
        parent::setUp();
        $this->loadFixtures();
    }

    // ...
}
```

### Expected result
I would expect the bundle to backup only database schema, not test data. How can I achieve this?
