### ISSUE TITLE
Option memory of SQLite not working

### ISSUE THREAD

**Issue by lukepass** [liip/LiipTestFixturesBundle#95]
Hello, in Symfony 3.4, I tried using the `memory` option in order to make my tests faster but an error occurred:

```
1) Tests\AppBundle\Controller\DefaultControllerTest::testIndex
copy(mydb): failed to open stream: No such file or directory
```

My test config is the following:

```
imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSION
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_db:
        sqlite: liip_functional_test.services_database_backup.sqlite

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                memory:   true
security:
    firewalls:
        main:
            http_basic: ~
```

Thank you.
